### PR TITLE
include messages in incoming and outgoing messages

### PR DESCRIPTION
**Pull request by alexmorten**

### CODE REVIEW

**Comment by good-praxis** [comment]
Is timestamp format currently validated?

**Comment by alexmorten** [comment]
The timestamp has to be an int, nothing else is validated.

**Comment by good-praxis** [comment]
So it's assumed to be a unix time int?

**Comment by alexmorten** [comment]
Yes

**Comment by alexmorten** [comment]
(in Nanoseconds)

**Pull request merged**
